baseURL = "https://statichunt.com/"
languageCode = "en-us"
title = "Static Hunt"
theme = "statichunt"
paginate = 18
summaryLength = 10
# enableGitInfo = false

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[params]
  segment_id = ""
  description = "Over 1000 themes and starters for Jamstack and static site generators."
  statichunt_button = true
  iframe_demo = true
  [theme_card]
    show_archetype_icons = false
    show_services_icons = false

[taxonomies]
  ssg = "ssg"
  cms = "cms"
  css = "css"
  archetype = "archetype"
  services = "services"

[outputFormats]
  [outputFormats.demo]
    name = "demo"
    mediaType = "text/html"
    isHTML = "true"
    path = "demo"
    permalinkable = "true"

[outputs]
  home = ["HTML","RSS","JSON"]
  section = ["HTML","RSS"]
  page = ["HTML", "demo"]

[frontmatter]
  lastmod = [":git", "lastmod", ":fileModTime", ":default"]

# Main Menu
[[menu.main]]
	name = "Themes"
	url = "/"
    weight = 1

[[menu.main]]
	name = "Resources"
	url = "/theme/"
    weight = 2

  [[menu.main]]
	name = "About"
	url = "/resources/"
    weight = 3
